// Generated by CoffeeScript 1.6.2
(function() {
  var Duel, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $('.side_tabs').tabs();

  $('#setting_enable_3d').change(function() {
    if (this.checked) {
      return $('.field').transition({
        scale: 2,
        translate: [116, 40],
        rotateX: 45
      });
    } else {
      return $('.field').transition({
        scale: 2,
        translate: [116, 40],
        rotateX: 0
      });
    }
  });

  Duel = (function(_super) {
    __extends(Duel, _super);

    function Duel() {
      _ref = Duel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Duel.avatar_url = 'http://my-card.in/users/:name.png';

    Duel.prototype.set_player_name = function(name) {
      return this.set_name('player', name);
    };

    Duel.prototype.set_opponent_name = function(name) {
      return this.set_name('opponent', name);
    };

    Duel.prototype.set_player_lp = function(lp) {
      return this.set_lp('player', lp);
    };

    Duel.prototype.set_opponent_lp = function(lp) {
      return this.set_lp('opponent', lp);
    };

    Duel.prototype.set_phase = function(phase) {
      $(".phase[data-phase!=" + phase + "]").removeClass('active');
      return $(".phase[data-phase=" + phase + "]").addClass('active');
    };

    Duel.prototype.set_turn = function(turn) {
      return $('#turn').html(turn);
    };

    Duel.prototype.set_name = function(player, name) {
      $("#" + player + "_name").html(name);
      return $("#" + player + "_avatar").attr('src', Duel.avatar_url.replace(':name', name));
    };

    Duel.prototype.set_lp = function(player, lp) {
      if (typeof lp === "string") {
        if (lp.slice(0, 2) === '+=') {
          lp = parseInt($("#" + player + "_lp").html()) + parseInt(lp.slice(2));
        } else if (lp.slice(0, 2) === '-=') {
          lp = parseInt($("#" + player + "_lp").html()) - parseInt(lp.slice(2));
        } else {
          lp = parseInt(lp);
        }
      }
      $("#" + player + "_lp").html(lp);
      return $("#" + player + "_lp_bar").animate({
        'width': "" + ((lp <= 0 ? 0 : lp >= 8000 ? 1 : lp / 8000) * 100) + "%"
      });
    };

    return Duel;

  })(Spine.Controller);

  this.duel = new Duel();

  $(document).ready(function() {
    return $('#setting_enable_3d').change();
  });

}).call(this);
